[agent]
  interval = "10s"  
  round_interval = true
  
  metric_batch_size = 1000  
  metric_buffer_limit = 10000  
  collection_jitter = "2s"  
  flush_interval = "10s"
  flush_jitter = "2s" 
  precision = "0s"
  
  hostname = ""  
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"] 
  database = "influx"             
  timeout = "5s"                   
  username = "admin"
  password = "admin"              


[[outputs.websocket]]
  flush_interval = "1s"
  url = "ws://localhost:3002/api/live/push/telegraf"
  data_format = "influx"
  [outputs.websocket.headers]
    Authorization = "Bearer secret"
[[inputs.cpu]]  
  percpu = true
  totalcpu = true 
  collect_cpu_time = false  
  report_active = false  
  core_tags = false

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
  
[[inputs.system]]
  
[[inputs.dns_query]]
    servers = ["8.8.8.8", "1.1.1.1"]
[[inputs.docker]]
    endpoint = "unix:///var/run/docker.sock"
[[inputs.exec]]
  commands = ["pgrep -c nginx"]
  name_override = "nr_processes"
  data_format = "value"
  data_type = "integer"
  interval = "5m"
  [inputs.exec.tags]
    instance = "Nginx"
[[inputs.exec]]
  commands = ["pgrep -c -u redis redis-server"]
  name_override = "nr_processes"
  data_format = "value"
  interval = "5m"
  [inputs.exec.tags]
    instance = "Redis"
[[inputs.exec]]
  commands = ["pgrep -c -u postgres postgres"]
  name_override = "nr_processes"
  data_format = "value"
  interval = "5m"
  [inputs.exec.tags]
    instance = "PostgreSQL"

[[inputs.http_response]]
    urls = "[https://google.com", "https://yahoo.com"]
    response_timeout = "10s"
    follow_redirects = true
[[inputs.internal]]
[[inputs.interrupts]]
[[inputs.kernel_vmstat]]
[[inputs.linux_sysctl_fs]]
[[inputs.mdstat]]
[[inputs.net]]
    ignore_protocol_stats = true
[[inputs.netstat]]
[[inputs.nstat]]