- name: "Installing apt's"
  apt:
      name: "{{ item }}"
      state: latest
  loop:
    - nvtop
    - lz4
    - neovim
    - auditd
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - smartmontools
    - htop
    - iotop
    - atop
    - nmon
    - sysstat
    - net-tools
    - iftop
    - nethogs
    - tcpdump
    - lsof
    - ncdu
    - dstat
    - glances
    - ioping
    - stress-ng
    - ethtool
    - nload
    - bmon
  tags:
    - install_update_packages
